### ISSUE TITLE
goldin_64 fails on macOS High Sierra 10.13 with APFS file system

### ISSUE THREAD

**Issue by Shailesh-Venugopal** [packagesdev/goldin#1]
The stat call on macOS High Sierra 10.13 returns 'apfs' as the file system name, 
so the check if (strcmp(tStatFileSystem.f_fstypename,"hfs")!=0) is always triggered
and the tool returns 254 - which is incorrect.

**Comment by Shailesh-Venugopal** [comment]
Did not notice an apfs branch in progress - so closing

**Comment by packagesdev** [comment]
It was part of the problem, indeed. The other issues with this version was that it was based on deprecated Carbon APIs dealing with Resources. The apfs branch now uses xattr.h.
