### ISSUE TITLE
How to join split metadata on macOS 10.12+?

### ISSUE THREAD

**Issue by aonez** [packagesdev/goldin#3]
Since `FixupResourceForks` is no more present (at least where it was before), do you have any idea of how to apply again the split metadata?

**Comment by packagesdev** [comment]
Are you looking for a solution that is available with a clean OS install or with an external tool?

I had a quick look at the FixupResourceForks command line tool. I can see some reasons why Apple may explain why they removed it:
- it's a 32-bit application.
- it used deprecated Carbon APIs.
- it contains a test that prevents it from working with non HFS volumes.

Then there are some other issues with this tool:

- the -q option detection is a bit too lenient (i.e. you can use -q, -quiet or -quovadis)
- it incorrectly assumes that there are always at least 82 bytes in the ._ Apple Double file
- it apparently incorrectly assumes that there are always 2 entries in the ._ Apple double file.
- it incorrectly assumes that one of these 2 entries is a Resource Fork.
- there's a -norecurse hidden option that is detected but not implemented.

That being said, it should not be too difficult to build a tool doing the same thing.

**Comment by aonez** [comment]
> Are you looking for a solution that is available with a clean OS install or with an external tool?

I don't care wether it's bundled or external. Usually better external, if it can be tweaked (open source).

Thanks for that great analysis, makes sense. I suppose `FixupResourceForks` was done long ago but not much maintained. But killing it and sharing it's code would have been better that just killing it... 😛

I have no knowledge about Mac metadata to craft a tool, but I presume your tool has all the code already, so maybe just need to be done in the "inverse way"?

**Comment by packagesdev** [comment]
Yes, it's basically the inverse way with a few checks.

I might have something to play with in the next few days (I have already a working version but I need to make a lot of tests and add error reports to the existing code).

When ready, this will be available here:

https://github.com/packagesdev/goldout

**Comment by packagesdev** [comment]
It's ready.

**Comment by aonez** [comment]
Gonna test it as soon as possible! 👍🏼
